# Core scalars and enums used across the schema

scalar JSON
scalar Anytype
scalar LangString
scalar Time

# Element type enum - WinCC OA data types
enum ElementType {
  STRUCT
  CHAR
  UINT
  INT
  FLOAT
  BOOL
  BIT32
  STRING
  TIME
  DPID
  LANGSTRING
  BLOB
  BIT64
  LONG
  ULONG
  CHAR_STRUCT
  UINT_STRUCT
  INT_STRUCT
  FLOAT_STRUCT
  BOOL_STRUCT
  BIT32_STRUCT
  STRING_STRUCT
  TIME_STRUCT
  DPID_STRUCT
  DYN_CHAR
  DYN_UINT
  DYN_INT
  DYN_FLOAT
  DYN_BOOL
  DYN_BIT32
  DYN_STRING
  DYN_TIME
  DYN_DPID
  DYN_LANGSTRING
  DYN_BLOB
  DYN_BIT64
  DYN_LONG
  DYN_ULONG
  DYN_CHAR_STRUCT
  DYN_UINT_STRUCT
  DYN_INT_STRUCT
  DYN_FLOAT_STRUCT
  DYN_BOOL_STRUCT
  DYN_BIT32_STRUCT
  DYN_STRING_STRUCT
  DYN_TIME_STRUCT
  DYN_DPID_STRUCT
  LANGSTRING_STRUCT
  DYN_LANGSTRING_STRUCT
  BLOB_STRUCT
  DYN_BLOB_STRUCT
  BIT64_STRUCT
  DYN_BIT64_STRUCT
  LONG_STRUCT
  DYN_LONG_STRUCT
  ULONG_STRUCT
  DYN_ULONG_STRUCT
  TYPEREF
}

# Control type enum - WinCC OA control variable types
enum CtrlType {
  TIME_VAR
  BOOL_VAR
  INT_VAR
  UINT_VAR
  FLOAT_VAR
  STRING_VAR
  BIT32_VAR
  CHAR_VAR
  DYN_TIME_VAR
  DYN_BOOL_VAR
  DYN_INT_VAR
  DYN_UINT_VAR
  DYN_FLOAT_VAR
  DYN_STRING_VAR
  DYN_BIT32_VAR
  DYN_CHAR_VAR
  ATIME_VAR
  LANGSTRING_VAR
  BLOB_VAR
  LONG_VAR
  ULONG_VAR
  BIT64_VAR
}
